First convection model
cometz95/rce pull request #1
Opened 2024-03-15 20:38 UTC by cometz95

2024-03-15 23:11 UTC, chengcli requested changes

2024-03-15 23:11 UTC, chengcli commented on data/amars.yaml
You can remove this file since you already have it in examples

2024-03-15 23:11 UTC, chengcli commented on src/harp/set_spectral_properties.cpp
> +        // Real kcoeff = 5;
remove this

2024-03-18 22:24 UTC, chengcli approved these changes

2024-03-18 22:52 UTC, cometz95 commented
merge amars convective model to canoe
-add input file for multi species condensation
-add vapor pressure files

2024-03-18 22:52 UTC, cometz95 commented
merge amars convective model to canoe
-add input file for multi species condensation
-add vapor pressure files

2024-03-18 22:52 UTC, closed without merging